services:
  web_app:
    image: modern-education:latest
    ports:
      - 3000:3000
    environment:
      - APP_DATABASE_HOST=postgres
      - APP_DATABASE_PORT=5432
      - APP_DATABASE_USERNAME=postgres
      - APP_DATABASE_PASSWORD=123456
    links:
      - postgres:postgres
  
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=modern_education_db

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - 80:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=darpa@darpa.com
      - PGADMIN_DEFAULT_PASSWORD=123456789
    links:
      - postgres:postgres